apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlesheetclone-deployment
  namespace: "2401025"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlesheetclone
  template:
    metadata:
      labels:
        app: googlesheetclone
    spec:
      containers:
        - name: googlesheetclone
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401025-project/googlesheetclone:latest
          ports:
            - containerPort: 80
